# Extension configuration file.
# Visit the "Extension configuration file (extension.toml)" section for more details:
# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html
#

[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "graph"
title = "Example Node Template"
description = "Example template for python omnigraph extension with an exemple node"
authors = ["contact@rodriguez-esteban.com"]
repository = "https://github.com/Z3ZEL/isaac-sim-omnigraph-exts-template"
keywords = ["template","omnigraph"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.graph" = {}
"omni.graph.tools" = {}

# define the Python module that the extension provides
[[python.module]]
name = "com.example.ext"

[settings]
exts."com.example.ext".timeout = 5

